# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "hadoop-cent64-x64"
#box = "dspit-rhel64-x64"

Vagrant.configure("2") do |config|

  config.yum_proxy.http     = ""
  #config.yum_proxy.http     = "http://130.98.36.106:48254/"
  #config.yum_proxy.http     = "http://noevipncp2n.edf.fr:3128/"
  #config.proxy.http     = "http://noevipncp2n.edf.fr:3128/"
  #config.proxy.https    = "http://noevipncp2n.edf.fr:3128/"
  #config.proxy.http     = "http://pcyvipncp2n.edf.fr:3128/"
  #config.proxy.https    = "http://pcyvipncp2n.edf.fr:3128/"
  #config.proxy.no_proxy = "localhost,127.0.0.1,.ryba"
  
  # See:
  # http://devops.me/2011/10/10/vagrant-tricks-and-troubleshooting/
  # http://cbednarski.com/articles/creating-vagrant-base-box-for-centos-62/
  
  # config.ssh.default.username = "wdavidw"
  # config.ssh.default.private_key_path = "~/.ssh/id_rsa"
  
  config.vbguest.no_remote = true
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.provider "virtualbox" do |v|
    v.memory = 1536
    v.cpus = 2
  end
  # config.vm.provider "docker" do |d|
  #   # v.memory = 1536
  #   # v.cpus = 2
  #   #d.build_dir = "."
  # end
  # config.vm.define :ryba do |node|
  #   node.vm.box = "trusty"
  #   node.vm.hostname = "ryba.ryba"
  #   node.vm.network :private_network, ip: "10.10.10.10"
  #   node.vm.network :forwarded_port, guest: 22, host: 24010, auto_correct: true
  # end
  config.vm.define :master1 do |node|
    node.vm.box = box
    node.vm.hostname = "master1.ryba"
    node.vm.network :private_network, ip: "10.10.10.11"
    node.vm.network :forwarded_port, guest: 22, host: 24011, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 1536
    end
  end
  config.vm.define :master2 do |node|
    node.vm.box = box
    node.vm.hostname = "master2.ryba"
    node.vm.network :private_network, ip: "10.10.10.12"
    node.vm.network :forwarded_port, guest: 22, host: 24012, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 2304
    end
  end
  config.vm.define :master3 do |node|
    node.vm.box = box
    node.vm.hostname = "master3.ryba"
    node.vm.network :private_network, ip: "10.10.10.13"
    node.vm.network :forwarded_port, guest: 22, host: 24013, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 1536
    end
  end
  config.vm.define :front1 do |node|
    #node.vm.provider "docker" do |d|
    #  d.image = "fgrehm/vagrant-ubuntu:precise"
    #  d.has_ssh = true
    #  d.remains_running = true
    #end
    node.vm.box = box
    node.vm.hostname = "front1.ryba"
    node.vm.network :private_network, ip: "10.10.10.14"
    node.vm.network :forwarded_port, guest: 22, host: 24014, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 1024
    end
  end
  config.vm.define :worker1 do |node|
    node.vm.box = box
    node.vm.hostname = "worker1.ryba"
    node.vm.network :private_network, ip: "10.10.10.16"
    node.vm.network :forwarded_port, guest: 22, host: 24015, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 2048
    end
  end
  config.vm.define :worker2 do |node|
    node.vm.box = box
    node.vm.hostname = "worker2.ryba"
    node.vm.network :private_network, ip: "10.10.10.17"
    node.vm.network :forwarded_port, guest: 22, host: 24016, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 2048
    end
  end
end
