# -*- mode: ruby -*-
# vi: set ft=ruby :

# ./bin/vagrant box add centos65-x86_64-50g https://googledrive.com/host/0B4tZlTbOXHYWVGpHRWZuTThGVUE/centos65_virtualbox_50G.box

box = "centos65-x86_64-50g"

Vagrant.configure("2") do |config|

  #config.yum_proxy.http     = ENV['VAGRANT_HTTP_PROXY'] || ""
  #config.yum_proxy.https     = ENV['VAGRANT_HTTPS_PROXY'] || ""
  #config.yum_proxy.no_proxy     = ENV['VAGRANT_HTTP_NO_PROXY'] || ""
  
  # See:
  # http://devops.me/2011/10/10/vagrant-tricks-and-troubleshooting/
  # http://cbednarski.com/articles/creating-vagrant-base-box-for-centos-62/

  config.vm.synced_folder ".", "/vagrant", disabled: true
  config.ssh.insert_key = false
  # Virtualbox Configuration
  config.vm.provider :virtualbox do |vb|
    config.vbguest.no_remote = true
    config.vbguest.auto_update = false
    
  end
  #config.vbguest.no_remote = true
  #config.vbguest.auto_update = false
  # Libvirt Configuration
  config.vm.provider :libvirt do |libvirt|
    # Don't forget to create your storage pool
    libvirt.storage_pool_name="ryba-cluster"
    libvirt.uri="qemu:///system"
    # NOT WORKING BUT SHOULD: libvirt.graphics_type= 'none' 
    # if ARGV[0] == "up"
    #  config.vm.provision "shell", path: "setswap.sh"
    # end
  end
  config.vm.define :master1 do |node|
    node.vm.box = box
    node.vm.hostname = "master1.ryba"
    node.vm.network :private_network, ip: "10.10.10.11"
    node.vm.network :forwarded_port, guest: 22, host: 24011, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.name = node.vm.hostname
      d.memory = 1280
    end
    node.vm.provider "libvirt" do |d|
      d.memory = 1536
      d.graphics_port = 5911
    end
  end
  config.vm.define :master2 do |node|
    node.vm.box = box
    node.vm.hostname = "master2.ryba"
    node.vm.network :private_network, ip: "10.10.10.12"
    node.vm.network :forwarded_port, guest: 22, host: 24012, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.name = node.vm.hostname
      d.memory = 1280
    end
    node.vm.provider "libvirt" do |d|
      d.memory = 1536
      d.graphics_port = 5912
    end
  end
  config.vm.define :master3 do |node|
    node.vm.box = box
    node.vm.hostname = "master3.ryba"
    node.vm.network :private_network, ip: "10.10.10.13"
    node.vm.network :forwarded_port, guest: 22, host: 24013, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.name = node.vm.hostname
      d.memory = 1792
    end
    node.vm.provider "libvirt" do |d|
      d.memory = 2048
      d.graphics_port = 5913
    end
  end
  config.vm.define :front1 do |node|
    node.vm.box = box
    node.vm.hostname = "front1.ryba"
    node.vm.network :private_network, ip: "10.10.10.14"
    node.vm.network :forwarded_port, guest: 22, host: 24014, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.name = node.vm.hostname
      d.memory = 512
    end
    node.vm.provider "libvirt" do |d|
      d.memory = 512
      d.graphics_port = 5914
    end
  end
  config.vm.define :worker1 do |node|
    node.vm.box = box
    node.vm.hostname = "worker1.ryba"
    node.vm.network :private_network, ip: "10.10.10.16"
    node.vm.network :forwarded_port, guest: 22, host: 24015, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.name = node.vm.hostname
      d.customize ["modifyvm", :id, "--memory", 1792]
      d.customize ["modifyvm", :id, "--cpus", 3]
      d.customize ["modifyvm", :id, "--ioapic", "on"]
    end
    node.vm.provider "libvirt" do |d|
      d.memory = 2048
      d.cpus = 2
      d.graphics_port = 5916
    end
  end
  config.vm.define :worker2 do |node|
    node.vm.box = box
    node.vm.hostname = "worker2.ryba"
    node.vm.network :private_network, ip: "10.10.10.17"
    node.vm.network :forwarded_port, guest: 22, host: 24016, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.name = node.vm.hostname
      d.customize ["modifyvm", :id, "--memory", 1792]
      d.customize ["modifyvm", :id, "--cpus", 3]
      d.customize ["modifyvm", :id, "--ioapic", "on"]
    end
    node.vm.provider "libvirt" do |d|
      d.memory = 2048
      d.cpus = 2
      d.graphics_port = 5917
    end
  end
end
