# -*- mode: ruby -*-
# vi: set ft=ruby :

box = "centos65-x86_64"

Vagrant.configure("2") do |config|

  #config.yum_proxy.http     = ENV['VAGRANT_HTTP_PROXY'] || ""
  #config.yum_proxy.https     = ENV['VAGRANT_HTTPS_PROXY'] || ""
  #config.yum_proxy.no_proxy     = ENV['VAGRANT_HTTP_NO_PROXY'] || ""
  
  # See:
  # http://devops.me/2011/10/10/vagrant-tricks-and-troubleshooting/
  # http://cbednarski.com/articles/creating-vagrant-base-box-for-centos-62/

  config.vbguest.no_remote = true
  config.vbguest.auto_update = false
  config.vm.synced_folder ".", "/vagrant", disabled: true
  
  config.vm.define :master1 do |node|
    node.vm.box = box
    node.vm.hostname = "master1.ryba"
    node.vm.network :private_network, ip: "10.10.10.11"
    node.vm.network :forwarded_port, guest: 22, host: 24011, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 1152
    end
  end
  config.vm.define :master2 do |node|
    node.vm.box = box
    node.vm.hostname = "master2.ryba"
    node.vm.network :private_network, ip: "10.10.10.12"
    node.vm.network :forwarded_port, guest: 22, host: 24012, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 1152
    end
  end
  config.vm.define :master3 do |node|
    node.vm.box = box
    node.vm.hostname = "master3.ryba"
    node.vm.network :private_network, ip: "10.10.10.13"
    node.vm.network :forwarded_port, guest: 22, host: 24013, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 1152
    end
  end
  config.vm.define :front1 do |node|
    node.vm.box = box
    node.vm.hostname = "front1.ryba"
    node.vm.network :private_network, ip: "10.10.10.14"
    node.vm.network :forwarded_port, guest: 22, host: 24014, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.memory = 512
    end
  end
  config.vm.define :worker1 do |node|
    node.vm.box = box
    node.vm.hostname = "worker1.ryba"
    node.vm.network :private_network, ip: "10.10.10.16"
    node.vm.network :forwarded_port, guest: 22, host: 24015, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.customize ["modifyvm", :id, "--memory", 2048]
      d.customize ["modifyvm", :id, "--cpus", 2]
      d.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
  config.vm.define :worker2 do |node|
    node.vm.box = box
    node.vm.hostname = "worker2.ryba"
    node.vm.network :private_network, ip: "10.10.10.17"
    node.vm.network :forwarded_port, guest: 22, host: 24016, auto_correct: true
    node.vm.provider "virtualbox" do |d|
      d.customize ["modifyvm", :id, "--memory", 2048]
      d.customize ["modifyvm", :id, "--cpus", 2]
      d.customize ["modifyvm", :id, "--ioapic", "on"]
    end
  end
end
